spec:
  template:
    spec:
      containers:
      -
        resources:
          requests:
            cpu: "0.2"
            memory: 512Mi
          limits:
            cpu: "1.0"
            memory: 1024Mi
        env:
        - name: SPRING_APPLICATION_JSON
          value: '{"server":{"undertow":{"io-threads":1, "worker-threads":2 }}}'
        - name: TEST1_URL
          value: "http://www.google.ru"
        - name: THREAD_POOL_SIZE
          value: "4"
